export const countryIso3Map: Record<string, string> = {
  "afghanistan": "afg",
  "albania": "alb",
  "algeria": "dza",
  "andorra": "and",
  "angola": "ago",
  "antigua and barbuda": "atg",
  "argentina": "arg",
  "armenia": "arm",
  "australia": "aus",
  "austria": "aut",
  "azerbaijan": "aze",
  "bahamas": "bhs",
  "bahrain": "bhr",
  "bangladesh": "bgd",
  "barbados": "brb",
  "belarus": "blr",
  "belgium": "bel",
  "belize": "blz",
  "benin": "ben",
  "bhutan": "btn",
  "bolivia": "bol",
  "bosnia and herzegovina": "bih",
  "botswana": "bwa",
  "brazil": "bra",
  "brunei": "brn",
  "bulgaria": "bgr",
  "burkina faso": "bfa",
  "burundi": "bdi",
  "cabo verde": "cpv",
  "cambodia": "khm",
  "cameroon": "cmr",
  "canada": "can",
  "central african republic": "caf",
  "chad": "tcd",
  "chile": "chl",
  "china": "chn",
  "colombia": "col",
  "comoros": "com",
  "congo": "cog",
  "costa rica": "cri",
  "croatia": "hrv",
  "cuba": "cub",
  "cyprus": "cyp",
  "czechia": "cze",
  "czech republic": "cze",
  "denmark": "dnk",
  "djibouti": "dji",
  "dominica": "dma",
  "dominican republic": "dom",
  "ecuador": "ecu",
  "egypt": "egy",
  "el salvador": "slv",
  "equatorial guinea": "gnq",
  "eritrea": "eri",
  "estonia": "est",
  "eswatini": "swz",
  "ethiopia": "eth",
  "fiji": "fji",
  "finland": "fin",
  "france": "fra",
  "gabon": "gab",
  "gambia": "gmb",
  "georgia": "geo",
  "germany": "deu",
  "ghana": "gha",
  "greece": "grc",
  "grenada": "grd",
  "guatemala": "gtm",
  "guinea": "gin",
  "guinea-bissau": "gnb",
  "guyana": "guy",
  "haiti": "hti",
  "honduras": "hnd",
  "hungary": "hun",
  "iceland": "isl",
  "india": "ind",
  "indonesia": "idn",
  "iran": "irn",
  "iraq": "irq",
  "ireland": "irl",
  "israel": "isr",
  "italy": "ita",
  "jamaica": "jam",
  "japan": "jpn",
  "jordan": "jor",
  "kazakhstan": "kaz",
  "kenya": "ken",
  "kiribati": "kir",
  "kuwait": "kwt",
  "kyrgyzstan": "kgz",
  "laos": "lao",
  "latvia": "lva",
  "lebanon": "lbn",
  "lesotho": "lso",
  "liberia": "lbr",
  "libya": "lby",
  "liechtenstein": "lie",
  "lithuania": "ltu",
  "luxembourg": "lux",
  "madagascar": "mdg",
  "malawi": "mwi",
  "malaysia": "mys",
  "maldives": "mdv",
  "mali": "mli",
  "malta": "mlt",
  "marshall islands": "mhl",
  "mauritania": "mrt",
  "mauritius": "mus",
  "mexico": "mex",
  "micronesia": "fsm",
  "moldova": "mda",
  "monaco": "mco",
  "mongolia": "mng",
  "montenegro": "mne",
  "morocco": "mar",
  "mozambique": "moz",
  "myanmar": "mmr",
  "myanmar (burma)": "mmr",
  "namibia": "nam",
  "nauru": "nru",
  "nepal": "npl",
  "netherlands": "nld",
  "new zealand": "nzl",
  "nicaragua": "nic",
  "niger": "ner",
  "nigeria": "nga",
  "north korea": "prk",
  "north macedonia": "mkd",
  "norway": "nor",
  "oman": "omn",
  "pakistan": "pak",
  "palau": "plw",
  "panama": "pan",
  "papua new guinea": "png",
  "paraguay": "pry",
  "peru": "per",
  "philippines": "phl",
  "poland": "pol",
  "portugal": "prt",
  "qatar": "qat",
  "romania": "rou",
  "russia": "rus",
  "rwanda": "rwa",
  "saint kitts and nevis": "kna",
  "saint lucia": "lca",
  "saint vincent and the grenadines": "vct",
  "samoa": "wsm",
  "san marino": "smr",
  "sao tome and principe": "stp",
  "saudi arabia": "sau",
  "senegal": "sen",
  "serbia": "srb",
  "seychelles": "syc",
  "sierra leone": "sle",
  "singapore": "sgp",
  "slovakia": "svk",
  "slovenia": "svn",
  "solomon islands": "slb",
  "somalia": "som",
  "south africa": "zaf",
  "south korea": "kor",
  "south sudan": "ssd",
  "spain": "esp",
  "sri lanka": "lka",
  "sudan": "sdn",
  "suriname": "sur",
  "sweden": "swe",
  "switzerland": "che",
  "syria": "syr",
  "taiwan": "twn",
  "tajikistan": "tjk",
  "tanzania": "tza",
  "thailand": "tha",
  "timor-leste": "tls",
  "togo": "tgo",
  "tonga": "ton",
  "trinidad and tobago": "tto",
  "tunisia": "tun",
  "turkey": "tur",
  "turkmenistan": "tkm",
  "tuvalu": "tuv",
  "uganda": "uga",
  "ukraine": "ukr",
  "united arab emirates": "are",
  "united kingdom": "gbr",
  "united states": "usa",
  "uruguay": "ury",
  "uzbekistan": "uzb",
  "vanuatu": "vut",
  "vatican city": "vat",
  "venezuela": "ven",
  "vietnam": "vnm",
  "yemen": "yem",
  "zambia": "zmb",
  "zimbabwe": "zwe"
};
